export default function buildMobileInboxScreenProps({
  appHeaderTitle,
  bridges,
  selectedBridgeId,
  bridgeSignal,
  bridgeListSyncing,
  searchOpen,
  search,
  installPromptVisible,
  installBusy,
  isTodoScope,
  orderedProjects,
  selectedProjectId,
  draggingProjectChipId,
  draggingProjectChipOffsetX,
  lockProjectChipDropLayout,
  optimisticProjectChipOrder,
  projectChipRowRef,
  projectChipNodesRef,
  projectChipLayoutSnapshotRef,
  registerProjectChipNode,
  resolveProjectChipSlideOffsetX,
  onSelectTodoScope,
  onProjectChipClick,
  onProjectChipPointerDown,
  onProjectChipContextMenu,
  onOpenUtility,
  onSelectBridge,
  onOpenBridgeDropdown,
  onToggleSearch,
  onSearchChange,
  onInstallPwa,
  onDismissInstallPrompt,
  filteredTodoChats,
  selectedTodoChatId,
  formatRelativeTime,
  getTodoChatPreview,
  onOpenTodoChat,
  onRenameTodoChat,
  onDeleteTodoChat,
  filteredThreads,
  selectedThreadId,
  selectedThreadIds,
  threadSelectionMode,
  signalNow,
  registerThreadListItemNode,
  draggingThreadId,
  draggingThreadOffsetY,
  lockThreadListDropLayout,
  optimisticThreadOrderByProjectId,
  resolveThreadListItemSlideOffsetY,
  onStartThreadReorder,
  onMoveThreadReorder,
  onEndThreadReorder,
  onCancelThreadReorder,
  onOpenThread,
  onRenameThread,
  onDeleteThread,
  onToggleThreadSelection,
  onEnterThreadSelectionMode,
  threadListItemHelpers,
  bridgeAvailable,
  loadingState,
  threadBusy,
  selectedProject,
  onCancelThreadSelection,
  onDeleteSelectedThreads,
  onCreateInstantThread,
  onOpenNewThread,
  onOpenNewTodoChat
}) {
  const projectChipRowProps = {
    isTodoScope,
    orderedProjects,
    selectedProjectId,
    draggingProjectChipId,
    draggingProjectChipOffsetX,
    lockProjectChipDropLayout,
    optimisticProjectChipOrder,
    projectChipRowRef,
    projectChipNodesRef,
    projectChipLayoutSnapshotRef,
    registerProjectChipNode,
    resolveProjectChipSlideOffsetX,
    onSelectTodoScope,
    onProjectChipClick,
    onProjectChipPointerDown,
    onProjectChipContextMenu
  };

  const chromeProps = {
    appHeaderTitle,
    bridges,
    selectedBridgeId,
    bridgeSignal,
    bridgeListSyncing,
    searchOpen,
    search,
    installPromptVisible,
    installBusy,
    projectChipRowProps,
    onOpenUtility,
    onSelectBridge,
    onOpenBridgeDropdown,
    onToggleSearch,
    onSearchChange,
    onInstallPwa,
    onDismissInstallPrompt
  };

  const todoListProps = {
    chats: filteredTodoChats,
    selectedTodoChatId,
    formatRelativeTime,
    getTodoChatPreview,
    onOpenTodoChat,
    onRenameTodoChat,
    onDeleteTodoChat
  };

  const threadListProps = {
    threads: filteredThreads,
    selectedThreadId,
    selectedThreadIds,
    threadSelectionMode,
    signalNow,
    registerThreadListItemNode,
    draggingThreadId,
    draggingThreadOffsetY,
    transitionLocked: lockThreadListDropLayout || Boolean(optimisticThreadOrderByProjectId[selectedProjectId]),
    resolveThreadListItemSlideOffsetY,
    onStartThreadReorder,
    onMoveThreadReorder,
    onEndThreadReorder,
    onCancelThreadReorder,
    onOpenThread,
    onRenameThread,
    onDeleteThread,
    onToggleThreadSelection,
    onEnterThreadSelectionMode,
    threadListItemHelpers
  };

  const listProps = {
    isTodoScope,
    bridgeAvailable,
    loadingState,
    todoListProps,
    threadListProps
  };

  const actionBarProps = {
    threadSelectionMode,
    isTodoScope,
    threadBusy,
    selectedThreadCount: selectedThreadIds.length,
    selectedProjectReady: Boolean(selectedProject),
    bridgeAvailable,
    selectedProjectId,
    onCancelThreadSelection,
    onDeleteSelectedThreads,
    onCreateInstantThread,
    onOpenNewThread,
    onOpenNewTodoChat
  };

  return {
    chromeProps,
    listProps,
    actionBarProps
  };
}
